
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: åšå®¢
      icon: fa-solid fa-rss
      url: /
    - name: åˆ†ç±»
      icon: fa-solid fa-folder-open
      url: categories/
    - name: æ ‡ç­¾
      icon: fa-solid fa-tags
      url: tags/
    - name: å½’æ¡£
      icon: fa-solid fa-archive
      url: archives/
    - name: å‹é“¾
      icon: fa-solid fa-link
      url: friends/
    - name: å…³äº
      icon: fa-solid fa-info-circle
      url: about/
  search: Search...   # Search bar placeholder
############################### Navigation Bar ############################### > end


############################### Cover ############################### > start
cover:
  title: 'zeroloard & qiufeng'
  subtitle: ''
  search: ~~~ # search bar placeholder
  features:
    - name: åšå®¢
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
############################### Cover ############################### > end

############################### Article Layout ############################### > start
# æ–‡ç« å¸ƒå±€
article:
  # æ–‡ç« åˆ—è¡¨é¡µé¢çš„æ–‡ç« å¡ç‰‡å¸ƒå±€æ–¹æ¡ˆ
  preview:
    author: true # true, false
  # æ–‡ç« è¯¦æƒ…é¡µé¢çš„æ–‡ç« å¡ç‰‡æœ¬ä½“å¸ƒå±€æ–¹æ¡ˆ
  body:
    # æ–‡ç« é¡¶éƒ¨ä¿¡æ¯
    top_meta: [author, category, counter, wordcount, date]
    # æ–‡ç« åº•éƒ¨ä¿¡æ¯
    bottom_meta: [updated, tags, share]
    footer_widget:
      related_posts:
        enable: true
      copyright:
        enable: true
    meta_library:
      # é»˜è®¤æ–‡ç« ä½œè€…ï¼ˆå¯åœ¨ _data/author.yaml ä¸­å¢åŠ å…¶ä»–ä½œè€…ï¼Œå¹¶åœ¨ front-matter ä¸­è®¾ç½®ï¼‰
      # https://volantis.js.org/advanced-settings/#å¤šäººååŒ
      author:
        avatar: volantis-static/media/org.volantis/blog/favicon/apple-touch-icon.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
        name: 'zerolord & qiufeng'
        url: /
############################### Article Layout ############################### > end

############################### Sidebar ############################### > start
sidebar:
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      social:
        - icon: fa-solid fa-rss
          url: /atom.xml
        - icon: fab fa-github
          url: https://github.com/zerolord-qiufeng/
        - icon: fa-solid fa-headphones-alt
          url: /
    # ---------------------------------------
    # webinfo widget
    webinfo:
      type:
        runtime:
          enable: false
          data: '2024/01/01'    # å¡«å†™å»ºç«™æ—¥æœŸ
          text: 'å·²è¿è¡Œæ—¶é—´ï¼š'
          unit: 'å¤©'
    # ---------------------------------------
    # Memos widget
    memos_carousel:
      url: 'https://blog.qiufeng.xyz/' # æ›¿æ¢åŸè‡ªå·±çš„åŸŸåï¼Œä¹Ÿå¯ä»¥ç”¨æœè€å¸ˆçš„å¹³å°æ‰˜ç®¡
      creatorId: 'qiufeng' # æ›¿æ¢æˆè‡ªå·±çš„ç”¨æˆ·çš„ID
      tag: '' # è¦å±•ç¤ºçš„å†…å®¹çš„æ ‡ç­¾
      image: 'fa-solid fa-image' # å›¾ç‰‡æ›¿æ¢æˆå›¾æ ‡
      link: 'fa-solid fa-link' # é“¾æ¥æ›¿æ¢æˆå›¾æ ‡
      placeholder: 'è¯´è¯´åŠ è½½ä¸­...' # å ä½ç¬¦

############################### Sidebar ############################### > end

############################### Site Footer ############################### > start
site_footer:
  # site source
  source: https://github.com/zerolord-qiufeng/blog/
  # site copyright
  copyright: '[Copyright Â© since 2024 zerolord-qiufeng](/)'
############################### Site Footer ############################### > end

############################### Plugins ############################### > start
plugins:
  ######## Plugins for Count:
  # npm i hexo-wordcount
  wordcount:
    enable: true

  busuanzi:
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    enable: true

  # fontawesome V6:  https://fontawesome.com/docs/web/style/animate
  # fontawesome animation for fontawesome V5
  fontawesome_animation:
    enable: true
  # Typing Effects
  comment_typing:
    enable: true

  # æš—é»‘æ¨¡å¼ darkmode
  # å¼€å…³æŒ‰é’®ï¼šåœ¨ navbar.menu ä¸­æ·»åŠ ï¼š
  # - name: æš—é»‘æ¨¡å¼ # å¯è‡ªå®šä¹‰
  #   icon: fa-solid fa-moon # å¯è‡ªå®šä¹‰
  #   toggle: darkmode
  darkmode:
    enable: true

  # Artitalk https://artitalk.js.org
  # é…ç½®è¿‡ç¨‹è¯·å‚è€ƒï¼šhttps://artitalk.js.org/doc.html
  # ä½¿ç”¨è¿‡æ—§ç‰ˆæœ¬çš„è¯·ä¿®æ”¹Leancloud shuoshuo classéƒ¨åˆ†åˆ—åï¼šhttps://artitalk.js.org/release.html
  # é™¤appIDå’ŒappKEYå¤–å‡ä¸ºé€‰å¡«é¡¹
  artitalk:
    # Set `plugins: ["artitalk"]` to enable in front-matter
    # é…ç½®é¡¹æŒ‰ç…§ymlæ ¼å¼ç»§ç»­å¡«å†™å³å¯
    appId: ogP8qj3veMh0LFpFWMPOyF0X-MdYXbMMI # your appID
    appKey: nHXLd3N3Jgh460t2iRQKWAtr # your appKEY
    # serverURL:  #leancloudç»‘å®šçš„apiè®¿é—®åŸŸåï¼Œä½¿ç”¨å›½é™…ç‰ˆçš„è¯ä¸éœ€è¦å¡«å†™
    # lang: # è¯­è¨€è®¾ç½®ï¼Œzhä¸ºæ±‰è¯­ï¼Œenä¸ºè‹±è¯­ï¼Œesä¸ºè¥¿ç­ç‰™è¯­ã€‚é»˜è®¤ä¸ºæ±‰è¯­
    # pageSize: #æ¯é¡µè¯´è¯´çš„æ˜¾ç¤ºæ•°é‡
    # shuoPla: #åœ¨ç¼–è¾‘è¯´è¯´çš„è¾“å…¥æ¡†ä¸­çš„å ä½ç¬¦
    # avatarPla: #è‡ªå®šä¹‰å¤´åƒurlçš„è¾“å…¥æ¡†çš„å ä½ç¬¦
    # motion: #åŠ è½½åŠ¨ç”»çš„å¼€å…³ï¼Œ1ä¸ºå¼€ï¼Œ0ä¸ºå…³ï¼Œé»˜è®¤ä¸ºå¼€
    # bgImg: #è¯´è¯´è¾“å…¥æ¡†èƒŒæ™¯å›¾ç‰‡url
    # color1: #è¯´è¯´èƒŒæ™¯é¢œè‰²1&æŒ‰é’®é¢œè‰²1
    # color2: #è¯´è¯´èƒŒæ™¯é¢œè‰²2&æŒ‰é’®é¢œè‰²2
    # color3: #è¯´è¯´å­—ä½“é¢œè‰²
    # cssUrl: #è‡ªå®šä¹‰cssæ¥å£

  # Memos https://usememos.com
  memos:
    # Set `plugins: ["memos"]` to enable in front-matter
    url: 'https://blog.qiufeng.xyz/' # æ›¿æ¢æˆè‡ªå·±çš„åŸŸåï¼Œä¹Ÿå¯ä»¥ç”¨æœè€å¸ˆçš„å¹³å°æ‰˜ç®¡
    limit: '10' # å±•ç¤ºæ•°é‡é™åˆ¶
    id: '1' # æ›¿æ¢æˆè‡ªå·±çš„ç”¨æˆ·çš„ID
############################### Plugins ############################### > end

############################### Comments ############################### > start
comments:
  title: <i class='fas fa-comments'></i> è¯„è®º
  subtitle:
  service: beaudar
  beaudar:
    repo: zerolord-qiufeng/blog
    issue-term: https://blog.qiufeng.xyz/comments
    branch: main
    order: desc
    theme:
      light: github-light
      dark: github-dark
    label: âœ¨ğŸ’¬âœ¨
############################### Comments ############################### > end
